from typing import List
from state import SearchResult




def format_search_result(search_results: List[SearchResult]) -> str:
    """This formats the results generated by the tavily. So that llm can understand it easily."""
    parts=[]
    for result in search_results:
        counter=1
        formatted=f"""
        ======== SOURCE {counter} =======\n
        TITLE : {result["title"]}\n
        URL : {result["url"]}\n
        SCORE : {result["score"]}\n
        CONTENT : {result["content"]}\n"""
        parts.append(formatted)
        counter+=1
    return "\n".join(parts)